### ISSUE TITLE
Missing 'read' file

### ISSUE THREAD

**Issue by andygmorris** [mariadb-developers/nodejs-quickstart#1]
Hi. Did the query/read example go missing?

**Comment by PieterBreugelmans** [comment]
I believe so yes, looking at the following:
https://github.com/mariadb-developers/nodejs-quickstart/commit/67e4d28a2ebcce67950b463122c2c6455cdedb94

**Comment by PieterBreugelmans** [comment]
> Hi. Did the query/read example go missing?

I believe so yes, looking at the following: https://github.com/mariadb-developers/nodejs-quickstart/commit/67e4d28a2ebcce67950b463122c2c6455cdedb94
